### PR TITLE
Dev eni private ips list enabled

### PR DESCRIPTION
**Pull request by jakeasarus**

### CODE REVIEW

**Comment by jakeasarus** [comment]
### Fix
This issue has been present for a long time because this module is not in use. 

The module does work and was used in the ventura siem connection to the ventura_prod_snypr workspace. here is the run:
https://app.terraform.io/app/thinkstack-co/workspaces/ventura_prod_snypr/runs/run-vvnWTp7yL1Lf9Mnu

The module worked, but there is an error because we need to re-import that ENI. Looks like maybe it was created in the console.

**Review by QuesoGrande83 — APPROVED** [review]
I like it!

**Comment by jakeasarus** [comment]
Proof that updated changes to ENI module work. 

https://github.com/thinkstack-co/ventura_prod_snypr/blob/0106b873c3c33cbb79426194f1cbb1415812e84a/main.tf#L83-L102

[TF RUN](https://app.terraform.io/app/thinkstack-co/workspaces/ventura_prod_snypr/runs/run-gA6kTaFzvoDGwb8P)

**Review by QuesoGrande83 — APPROVED** [review]
Looking good!

**Pull request merged**
